const NUMBERS_SET = "0123456789";
const UPPERCASE_LETTERS_SET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
const LOWERCASE_LETTERS_SET = "abcdefghijlkmnopqrstuvwxyz";
const SYMBOLS_SET = "@#$%&*";
export {
  NUMBERS_SET,
  SYMBOLS_SET,
  UPPERCASE_LETTERS_SET,
  LOWERCASE_LETTERS_SET,
};
