import Head from "next/head";
import PasswordGenerator from "../../components/PasswordGenerator";

export default function Home() {
  return (
    <>
      <Head>
        <title>Password Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@300;400;500&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@300;400;500;600&family=Work+Sans:wght@300;400;500&display=swap"
          rel="stylesheet"
        ></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Maven+Pro:wght@400;500&family=Montserrat:wght@300;400;500&family=Poppins:wght@400;500;600;700&family=Raleway:wght@400;500;600&display=swap&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <PasswordGenerator />
    </>
  );
}
